version: "3"

services:
  server:
    user: '33:33'
    build: ./server
    image: cosearch-server
    container_name: cosearch-server
    env_file:
      - ./server/.env.${MODE}
    restart: always
    network_mode: host
    volumes:
      - ./server:/server
    # - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
    # ports:
    #   - 8031:8031
    command: gunicorn main:"create_flask_app()" -b 0.0.0.0:8031 --timeout 30 --threads 2 --reload
