version: "3"

services:
  server:
    user: "1000:1000"
    build: ./server
    image: cosearch-server
    container_name: cosearch-server
    env_file:
      - ./server/.env.dev
    restart: always
    volumes:
      - ./server:/server
      - /run/mysqld:/run/mysqld
    ports:
      - 8031:5000
    command: gunicorn main:"create_flask_app()" -b 0.0.0.0:5000 --timeout 3000 --reload
